#cloud-config
# TODO: Convert this file to a Tera template (cloud-init.yml.tera) to inject dynamic values
# TODO: Replace hardcoded SSH public key with {{ ssh_public_key }} variable from SshConfig.ssh_pub_key_path
# TODO: This will enable dynamic SSH key injection instead of using the hardcoded testing key
# Commented out for faster VM creation during development
# package_update: true
# package_upgrade: true

# packages:
#   - curl
#   - wget
#   - git
#   - htop
#   - vim

users:
  - name: torrust
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      # TODO: Replace this hardcoded testing key with {{ ssh_public_key }} template variable
      # TODO: The variable should be populated from SshConfig.ssh_pub_key_path content
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCw16sai+XVnawp/P/Q23kcXKekygZ6ALmQAyslREo6kbG8s5RScsmbQqOQEcIwnV2Vo88eeWVzX0N0H1dIczRa/ezijBEsGefthzmz9Ix/vM4lodzTPQFtW8c2eYw7ESy12/2x5//UQQ3mxawEWsz5Ri8XuyBEy/Xh7xH/KpoektaocIOt2/WdCe8CvZdMLd7AviGcTdHFWRiOVrmHM1Pd8znqeA3/1KQP/M4Ae5q21oPjchGjVfPkGh/e62Wt+Wo/2lT30AyMO7JHA1tB1W4xANRQkOd1Kb/TrDLXfg0PaHQ+Irmycjp/H4KkcdB06nzYawXMN5csd/5TWKwkb9/vofp6GQNP731U8+JR4cxRfD107KoHroDSJpG2Fanb2PVBkSXAiJl29YrtoP9vUtSIemQCD/aXFtTcpSv7Y16bdp7v+0adCEHwBmodm9GzLL808FpI2ZCzCi+Ae98P3z+yPCxbrnVAahU8AM2NSbrfyH1w2eb4hJ22oPjdd//tBYtkE1TZBw+i3n0vRn04s5BfPRwwj5GISxacTOZm/YWvoE4UU9axtFXOtMUniVKL3ycA+LEfK7C4velOKbluyL8fYYu4pUxHnYOOkYYeRoi2jf3oagbABOpznloPd93wYP3NoUpIdtMZW+iCF0NnZkVLC9lm1FbTcnmrfNzFtGVKCQ== testing@torrust-testing-infra

runcmd:
  - echo "VM provisioned successfully" > /tmp/provision_complete
  - systemctl enable ssh
  - systemctl start ssh
