[workspace]
members = [
  "packages/linting",
]
resolver = "2"

[package]
name = "torrust-tracker-deploy"
version = "0.1.0"
edition = "2021"
description = "Torrust Tracker Deployment Infrastructure with Ansible and OpenTofu"
license = "MIT"
default-run = "torrust-tracker-deploy"

[[bin]]
name = "torrust-tracker-deploy"
path = "src/main.rs"

[[bin]]
name = "e2e-tests"
path = "src/bin/e2e_tests.rs"

[[bin]]
name = "linter"
path = "src/bin/linter.rs"

[dependencies]
tokio = { version = "1.0", features = [ "full" ] }
anyhow = "1.0"
clap = { version = "4.0", features = [ "derive" ] }
derive_more = "0.99"
rust-embed = "8.0"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tempfile = "3.0"
tera = "1.0"
thiserror = "1.0"
torrust-linting = { path = "packages/linting" }
tracing = "0.1"
