[package]
name = "torrust-testing-infra"
version = "0.1.0"
edition = "2021"
description = "Torrust Testing Infrastructure with Ansible and OpenTofu"
license = "MIT"
default-run = "torrust-testing-infra"
[[bin]]
name = "torrust-testing-infra"
path = "src/main.rs"
[[bin]]
name = "e2e-tests"
path = "src/bin/e2e_tests.rs"
[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
regex = "1.0"
dirs = "5.0"
tempfile = "3.0"
