#cloud-config
# Commented out for faster VM creation during development
# package_update: true
# package_upgrade: true

# packages:
#   - curl
#   - wget
#   - git
#   - htop
#   - vim

users:
  - name: torrust
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDVvNSEw9lRv0wIHXHle7jNpGBgQfJ5fsT4WlntGqzVW0smjSAy9GgsERUrkX8N4jz5NherZVJpzMGn6V69CiClyptXeUUuz+BmWAtBH8pIJf5quku4Xmmxg9+hlal5JtdqH5ZwSCrF0EFzb2fS/hTk9npwZknR5Av4Nk+iREM+EvB/rbOfnXU7xNezIJ6sZNt2zIH3bROsmthmffEegosSQ2KO4YGHv6mW0SV/O+X22RHelP/3tAMu/2mM1ecdMOib32IlG38PjHnlhB6gmUoQ1USsPILxhaZLdU7pKs7Jx3FRZHuPQHNqj8ZVMzYZ2ONZ+uYUzg+kocJGiqV20PiJBrzTvUzoknvzU7l8cI5smmrXdZ3EKtykdbLLe21T8hrL4KndYYKTeXRTM63kHjluvX/ZVr4jmnz3GHTwf1HFnTmrq7jSaF5n4Y82qEu1ps9KFSCx4fXHxUeSNIzIqF+AOOS0t1nVWgc+q22p9khgnKsakVrTK+WEbvGSqjEWkzh2J2MjCwuc0IJClBrpqNFyOW/+eZutbrDjX7NAxBYCJZd64tCC2/BAefvbCDWIR2t2XGY8JcaPH5MvRnXR391kq/savEe8527AIkp3ZaV99js1psUIv67434bggpPz1LwpQW2bBA9mxW1XFXZsDQEdefXUujmcb4EbuYcow+SAEw== testing-key-for-torrust-deploy

runcmd:
  - echo "VM provisioned successfully" > /tmp/provision_complete
  - systemctl enable ssh
  - systemctl start ssh