---
# Simplified Docker Installation Playbook for E2E Testing
# Based on successful Docker-in-Docker installation from:
# https://github.com/josecelano/test-docker-install-inside-vm-in-runner/blob/main/.github/workflows/test-docker-runtime-install.yml

- name: Install Docker (Simplified for E2E)
  hosts: all
  gather_facts: true
  become: true

  vars:
    # Simple installation approach
    use_simple_install: true

  tasks:
    - name: 🐳 Starting simplified Docker installation
      ansible.builtin.debug:
        msg: "🚀 Installing Docker CE via Ubuntu repositories on {{ inventory_hostname }}"

    - name: Force update apt cache for container environment
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
      when: ansible_os_family == "Debian"

    - name: Ensure universe repository is available
      ansible.builtin.shell: |
        apt-cache policy docker.io || echo "docker.io not found"
        apt list --installed | grep -E "(universe|multiverse)" | head -5 || echo "No universe/multiverse packages found"
      register: repo_check
      changed_when: false

    - name: Display repository check results
      ansible.builtin.debug:
        var: repo_check.stdout_lines

    - name: Install Docker from Ubuntu repositories
      ansible.builtin.apt:
        name:
          - docker.io
        state: present
        force_apt_get: true
      when: ansible_os_family == "Debian"
      register: docker_install

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      when: docker_install is succeeded
      ignore_errors: true # Ignore in container environments where systemd might not work

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
      when: docker_install is succeeded
      register: user_added_to_docker_group

    - name: Activate docker group membership immediately
      ansible.builtin.shell: |
        newgrp docker << 'EOF'
        docker --version
        EOF
      when: user_added_to_docker_group is changed
      ignore_errors: true

    - name: Test Docker installation
      ansible.builtin.shell: docker --version
      register: docker_test
      changed_when: false

    - name: Display installation result
      ansible.builtin.debug:
        msg: "✅ Docker installed successfully: {{ docker_test.stdout }}"
      when: docker_test is succeeded

    - name: Installation summary
      ansible.builtin.debug:
        msg: |
          ✅ Docker installation completed!
          📦 Installed: docker.io
          👤 User '{{ ansible_user }}' added to docker group
          🔧 Group membership activated with newgrp
          ℹ️  Note: Install Docker Compose separately using install-docker-compose.yml
