---
# Install Docker Compose via direct download (Modern approach for E2E testing)
# This playbook installs Docker Compose v2 directly from GitHub releases,
# which is the most reliable method for getting the modern plugin-based version

- name: Install Docker Compose (Direct download for E2E)
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: 🐋 Starting Docker Compose installation
      debug:
        msg: |
          🚀 Installing Docker Compose v2 via direct download on {{ inventory_hostname }}

    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      failed_when: false
      changed_when: false

    - name: Ensure Docker is installed
      fail:
        msg: "Docker must be installed before installing Docker Compose"
      when: docker_check.rc != 0

    - name: Create Docker CLI plugins directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Download Docker Compose v2 plugin
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
        timeout: 30

    - name: Test Docker Compose installation
      command: docker compose version
      register: compose_version
      changed_when: false

    - name: 🎉 Docker Compose installation completed
      debug:
        msg: |
          ✅ Docker Compose installed successfully!
          Version: {{ compose_version.stdout }}
          Command: docker compose (modern plugin syntax)
