[package]
name = "torrust-linting"
version = "0.1.0"
edition = "2021"
description = "Linting utilities for the Torrust Tracker Deploy project"
license = "MIT"

[lib]
name = "torrust_linting"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
regex = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
clap = { version = "4.0", features = [ "derive" ] }
